### ISSUE TITLE
Add pre-trained study design models to GitHub

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/paperetl#19]
Currently, the pre-trained study design models are stored on Kaggle. Put a copy of these files on the next GitHub release. This will allow automation/docker builds.

```
# Download pre-trained study design/attribute models
# https://www.kaggle.com/davidmezzetti/cord19-study-design/#attribute
# https://www.kaggle.com/davidmezzetti/cord19-study-design/#design
```

**Comment by nialov** [comment]
I am unable to download the pre-trained study design models because Kaggle refuses download of **attribute** and **design** models with a message: `Too many requests`.

**Comment by davidmezzetti** [comment]
I believe if you log into Kaggle you will be able to download them.
