### ISSUE TITLE
sample lines for running etl  server  and grobid instance

### ISSUE THREAD

**Issue by amscosta** [neuml/paperetl#53]
Apologies if my question is too silly.
In the description you wrote :
"PDF parsing relies on an existing GROBID instance to be up and running.
 It is assumed that this is running locally on the ETL server"
Can you provide some sample lines about how to do that?
Best regards

**Comment by davidmezzetti** [comment]
I usually download and build GROBID per these instructions: https://grobid.readthedocs.io/en/latest/Install-Grobid/

Then start it locally with `./gradlew run`

Alternatively, you can run it with Docker: https://grobid.readthedocs.io/en/latest/Run-Grobid/

**Comment by davidmezzetti** [comment]
Closing this issue as the question has been addressed.
